apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app
spec:
  selector:
    matchLabels:
      app: streamlit-app
  replicas: 1
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit-app
        image: streamlit-app:1.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: NodePort
  selector:
    app: streamlit-app
  ports:
  - name: streamlit-app
    port: 80
    nodePort: 30080
